Table extention
capsulajs/capsulahub-extensions pull request #28
Opened 2019-05-31 13:24 UTC by 95kach

2019-06-03 04:40 UTC, stephanebenayoun requested changes
Issue not ready

2019-06-05 07:25 UTC, lapanton approved these changes

2019-06-05 15:06 UTC, dmitriyslaym reviewed
We need to add release notes at the description of the PR

2019-06-05 15:06 UTC, dmitriyslaym commented on packages/table/.gitignore
> +lib/
We have .gitignore in the root - isn't it enough?

2019-06-05 15:06 UTC, dmitriyslaym commented on packages/table/cypress/integration/table.test.js
> +          .first()
this chain doesn't look good - use basically type something in the input and check it's content many times - you can extract this pattern in a separate helper (Command) and use it with some params (take a look at type Command in request-form package). This will improve the reusability and readability of the code.

2019-06-05 15:06 UTC, dmitriyslaym commented on packages/table/example/utils.ts
> +  data$: of(new Array(20).fill(null).map((_, i) => ({
are you emitting this data only once in data$ stream? (that's what of will result in). Don't you want to check that the changes in data$ will be handled correctly? (when you use **from** with a few emitions of Row instead of only **of**)

2019-06-05 15:06 UTC, dmitriyslaym commented on packages/table/package.json
> +    "start-example-server": "http-server './example' --p 1234 --cors",
```suggestion
    "start-example-server": "http-server --p 1234 --cors",
```

2019-06-05 15:06 UTC, dmitriyslaym commented on packages/table/package.json
> +    "build:dist": "rimraf dist && cross-env PACKAGE_NAME=$(echo \"${PWD##*/}\") webpack",
```suggestion
    "build:dist": "rimraf dist && cross-env PACKAGE_NAME=table webpack",
```

2019-06-05 15:06 UTC, dmitriyslaym commented on packages/table/package.json
> +    "build-example": "rimraf example/dist && cross-env PACKAGE_NAME=$(echo \"${PWD##*/}\") webpack --config webpack.config-example.js",
```suggestion
    "build-example": "rimraf example/dist && cross-env PACKAGE_NAME=table webpack --config webpack.config-example.js",
```

2019-06-05 15:06 UTC, dmitriyslaym commented on packages/table/src/Table.tsx
> +const mountPoint = 'web-table';
Do you have mount-point the same as the mount-point for web-component? Mount point in web-component should be internal only to render React component in it. And it should be unique, so I suggest to use some function to generate unique ID

2019-06-05 15:06 UTC, dmitriyslaym commented on packages/table/src/index.ts
> +import * as api from './api';
suggest to always use API instead of api

2019-06-05 15:06 UTC, dmitriyslaym commented on packages/table/tslint.json
> +{
we have it in the root, why do we need this dublication?

2019-06-06 08:16 UTC, 95kach commented on packages/table/example/utils.ts
> +  data$: of(new Array(20).fill(null).map((_, i) => ({
Make sense

2019-06-06 08:45 UTC, 95kach commented on packages/table/src/Table.tsx
> +const mountPoint = 'web-table';
I see I added `guid` function in utils package (as a beginning), but the final implementation of this random id logic is out of the scope of my feature. 

There no any package with this approach, so I suggest you create an issue to apply this logic in all packages.

2019-06-06 11:10 UTC, dmitriyslaym commented on packages/table/cypress/cypress.json
> +{}
why do you need it?

2019-06-06 11:13 UTC, dmitriyslaym approved these changes

2019-06-06 11:38 UTC, merged

2019-06-06 12:30 UTC, VictoriaBordian commented
Not tested yet

2019-06-06 13:48 UTC, VictoriaBordian reviewed
QA passed