Feature/logger
capsulajs/capsulahub-extensions pull request #3
Opened 2019-04-16 15:21 UTC by 95kach

2019-04-19 13:42 UTC, IrinaComindaru approved these changes

2019-04-21 07:03 UTC, MikeSquall commented on packages/logger/src/index.ts
> +export { LoggerProps } from "./types";
```suggestion
export { LoggerProps, Event } from "./types";
```
and remove the line 3

2019-04-21 07:03 UTC, MikeSquall commented on packages/logger/src/logger.tsx
> +const mountPoint = "web-logger";
This shouldn't be set outside of this file in order to make it configurable ?

2019-04-22 06:46 UTC, 95kach commented on packages/logger/src/logger.tsx
> +const mountPoint = "web-logger";
No. Actually doesn't matter how to call this as I understood, because it's internal id for mounting react component inside html element.

2019-04-22 06:54 UTC, MikeSquall approved these changes

2019-04-22 07:31 UTC, dmitriyslaym requested changes

2019-04-22 07:31 UTC, dmitriyslaym commented on packages/logger/cypress/integration/logger.test.ts
> +        .visit("/")
seems like you can implement this logic with **forEach** logic

2019-04-22 07:31 UTC, dmitriyslaym commented on packages/logger/package.json
> +    "build": "rimraf lib && cross-env BABEL_ENV=commonjs babel src/index.ts --out-dir lib --copy-files",
we will discuss on daily - I think the build process will be different

2019-04-22 07:31 UTC, dmitriyslaym commented on packages/logger/src/example/index.html
> +<!DOCTYPE html>
I think we will not keep index.html in this package

2019-04-22 07:31 UTC, dmitriyslaym commented on packages/logger/src/example/index.tsx
> +prepareWebComponent({
I think the logic of bootstrapping web component should be put separately from the component itself

2019-04-22 07:31 UTC, dmitriyslaym commented on packages/logger/src/logger.tsx
> +    const Component: any = this.props$
We will put strict type checking  and should avoid _any_ type now

2019-04-22 07:31 UTC, dmitriyslaym commented on packages/logger/src/types.ts
> +export interface Event {
Give a more descriptive name please

2019-04-22 07:31 UTC, dmitriyslaym commented on packages/logger/tsconfig.json
> +    "types": ["cypress", "node", "react", "react-dom"],
I think you have to install these types in package.json

2019-04-22 07:33 UTC, 95kach commented on packages/logger/src/example/index.html
> +<!DOCTYPE html>
so how to test it? with cypress without index.html

2019-04-22 07:34 UTC, 95kach commented on packages/logger/src/example/index.tsx
> +prepareWebComponent({
this already separated (folder name example)

2019-04-22 07:38 UTC, 95kach commented on packages/logger/tsconfig.json
> +    "types": ["cypress", "node", "react", "react-dom"],
fixed

2019-04-22 08:03 UTC, 95kach commented on packages/logger/src/example/index.tsx
> +prepareWebComponent({
I'm not including these files into the build.
@dmitriyslaym

2019-04-22 08:04 UTC, 95kach commented on packages/logger/src/example/index.html
> +<!DOCTYPE html>
I'm not including these files into the build.
@dmitriyslaym

2019-04-22 13:52 UTC, dmitriyslaym approved these changes

2019-04-22 13:53 UTC, merged