Fix config for Windows
capsulajs/capsulahub-extensions pull request #31
Opened 2019-06-05 12:17 UTC by dmitriyslaym

2019-06-05 15:46 UTC, 95kach approved these changes

2019-06-05 15:46 UTC, 95kach commented on base-webpack.config-example.js
> +  entry: `${packagePath}/public/index.ts`,
to be honest, in public should be `index.html` + compiled files 
index.html + compiled files in the perfect case should be on the same folder level.

it prevents issues with assets because I remember when you open the page you won't see the images because of the wrong path.

but I will ignore this because I want to see this issue resolved asap.

2019-06-05 15:58 UTC, idanilt requested changes
Too much copy past...
You don't need PACKAGE_NAME in the env, you don't have any bash you are writing JS

Just changed those (webpack config)
const packagePath = path.resolve(__dirname, `packages/${process.env.PACKAGE_NAME}`);

To
const name = require('package.json').name;
const packagePath = path.resolve(__dirname, `packages/${name}`);

2019-06-06 07:05 UTC, 95kach requested changes

2019-06-06 07:05 UTC, 95kach commented on base-webpack.config-example.js
> +      compress: true,
why we need compress? (dev env)
it's slow down the work.

usually compression and bundle optimization used in prod env.

2019-06-06 07:05 UTC, 95kach commented on packages/canvas/webpack.config-example.js
>  module.exports = {
try to use `module.exports = baseConfig` it should work too.

2019-06-06 07:11 UTC, VictoriaBordian approved these changes
QA passed

2019-06-06 07:53 UTC, 95kach approved these changes

2019-06-06 07:53 UTC, merged