upgrade capsulahub-ui to 0.6.8
capsulajs/capsulahub-extensions pull request #38
Opened 2019-06-11 12:24 UTC by 95kach

2019-06-11 12:25 UTC, dmitriyslaym approved these changes

2019-06-11 12:30 UTC, dmitriyslaym requested changes
Fix Travis

2019-06-11 14:27 UTC, dmitriyslaym commented on lerna.json
> +  "version": "independent"
@stephanebenayoun Was this change done by you? Can you please explain why?

2019-06-12 06:13 UTC, stephanebenayoun commented on lerna.json
> +  "version": "independent"
it was a mistake that need to be revert, it's ok

2019-06-12 06:13 UTC, stephanebenayoun approved these changes

2019-06-12 06:14 UTC, merged