[ Tests ] Env, Registry extension
capsulajs/capsulahub-extensions pull request #41
Opened 2019-06-16 14:58 UTC by MikeSquall

2019-06-17 12:57 UTC, MikeSquall commented on packages/environment-registry/tests/features/bootstrap.feature
> +  When EnvRegistry extension registers itself to the Workspace
```suggestion
  And EnvRegistry extension registers itself to the Workspace
```

2019-06-17 12:57 UTC, MikeSquall commented on packages/environment-registry/tests/features/bootstrap.feature
> +  And  EnvRegistry with register method and a given environment
```suggestion
  And  An environment with `envKey: dev` and `env: 'myEnv'`
```

2019-06-17 12:57 UTC, MikeSquall commented on packages/environment-registry/tests/features/bootstrap.feature
> +  And  EnvRegistry registers the environment
```suggestion
  When  EnvRegistry registers the environment
```

2019-06-17 12:57 UTC, MikeSquall commented on packages/environment-registry/tests/features/bootstrap.feature
> +  And  an EnvRegistry instance with this environment is available
```suggestion
  Then  Registration of the environment is performed with success
  And   Subscribing to environments method returns 'myEnv'
```

2019-06-17 13:26 UTC, dmitriyslaym requested changes
Suggest to add a scenario that this bootstrap function that is imported from the extension is resolved before the workspace.registerService resolves (that it doesn't wait workspace.registerService to be resolved internally).

2019-06-17 13:26 UTC, dmitriyslaym commented on packages/environment-registry/tests/features/bootstrap.feature
> +Scenario: EnvRegistry extension tries to register with bad configuration
don't need this case, it's us who make the request ion the bootstrap of extension, so it's our duty to make it correctly once.

2019-06-17 13:26 UTC, dmitriyslaym commented on packages/environment-registry/tests/features/bootstrap.feature
> +Scenario: EnvRegistry registers the provided environment
I'm sure that we need it here - we've already checked that we receive an instance of EnvRegistry service. So we expect to all of its functionality work correctly - it has been tested in this service implementation itself.

2019-06-17 14:23 UTC, dmitriyslaym requested changes
Scenario: EnvRegistry extension bootstrap function resolves correctly and triggers the registration of an instance of EnvRegistry in Workspace
  Given EnvRegistry extension
  And   A valid EnvRegistry configuration with a token and configProvider
  And   Workspace
  When  EnvRegistry extension bootstrap function is called with a Workspace as a first argument and envRegistryService configuration as a second argument
  Then  Correct EnvRegistry configuration is applied while creating an instance of EnvRegistryService
  And   The registration of EnvRegistryService in Workspace is triggered with the correct arguments
  And   The promise, that is returned from the call of the bootstrap function, resolves with no args
  And   The returned promise from a call of registration function is resolved (only after the resolve of bootstrap function)

Scenario: EnvRegistry extension bootstrap function rejects with an error if the creation of an instance of EnvRegistry throws an error
  Given EnvRegistry extension
  And   An invalid EnvRegistry configuration with a token and configProvider
  And   Workspace
  When  EnvRegistry extension bootstrap function is called with a Workspace as a first argument and envRegistryService configuration as a second argument
  And   The creation of EnvRegistryService instance fails with an error "Error1"
  Then  The promise, that is returned from the call of the bootstrap function, rejects with an error "Error1"
  And   The registration of the service in Workspace was not triggered

I've explained all the desired tests in Gherkin syntax, please make some arrangements to the syntax is it's required - and it will be the correct scenarios.

2019-06-18 06:37 UTC, dmitriyslaym approved these changes

2019-06-18 08:05 UTC, IrinaComindaru approved these changes

2019-06-18 08:47 UTC, merged