Modal Extension
capsulajs/capsulahub-extensions pull request #44
Opened 2019-06-18 07:46 UTC by 95kach

#37

2019-06-20 10:22 UTC, VictoriaBordian approved these changes
QA passed

2019-06-20 11:44 UTC, dmitriyslaym commented
Misha, please add release notes

2019-06-20 11:59 UTC, dmitriyslaym requested changes

2019-06-20 11:59 UTC, dmitriyslaym commented on packages/modal/cypress/fixtures/modal.js
> +// prettier-ignore
why // prettier-ignore?

2019-06-20 11:59 UTC, dmitriyslaym commented on packages/modal/cypress/integration/modal.test.js
> +describe('Modal TCs', () => {
For future - we already have a solution to write these tests in TS - do it for future extensions in the new capsulahub repo

2019-06-20 11:59 UTC, dmitriyslaym commented on packages/modal/cypress/integration/modal.test.js
> +          return cy.modalOpenend(modal);
modalOpenend ? Is it a typo?

2019-06-20 11:59 UTC, dmitriyslaym commented on packages/modal/cypress/integration/modal.test.js
> +            .find('[data-cy=modal-close]')
```suggestion
            .get('#web-modal [data-cy=modal-close]')
```

So you don't need .get('#web-modal')

2019-06-20 11:59 UTC, dmitriyslaym commented on packages/modal/cypress/integration/modal.test.js
> +            .modalClosed(modal);
expectIsModalClosed seems much more descriptive name

2019-06-20 11:59 UTC, dmitriyslaym commented on packages/modal/package.json
> +  "version": "0.0.2-alpha.0",
Why the version is not from 0.0.1?

2019-06-20 11:59 UTC, dmitriyslaym commented on packages/modal/src/api/ModalUIProps.ts
> +import { ModalStatus } from './index';
We need descriptions for API

2019-06-20 11:59 UTC, dmitriyslaym commented on packages/modal/src/example/index.ts
> +    if (!window.modalPropsSubject) {
instead of ts ignore it's better to declare the global vars that you want to use

2019-06-20 11:59 UTC, dmitriyslaym commented on packages/modal/src/example/index.ts
> +export { mountWebComponent };
why are exposing mountWebComponent globally and instantly call it on load of the script? You can just call mountWebComponent at the bottom of the file.

2019-06-20 11:59 UTC, dmitriyslaym commented on packages/modal/src/index.ts
> +export default Modal;
if this is n extension, why don't you wrap it in bootstrap function?

2019-06-20 11:59 UTC, dmitriyslaym commented on packages/modal/tslint.json
> +{
you don't need a separate tslint here

2019-06-20 12:09 UTC, 95kach commented on packages/modal/src/index.ts
> +export default Modal;
this is not an extension, this is just base component like `table` @dmitriyslaym

2019-06-20 12:12 UTC, 95kach commented on packages/modal/src/example/index.ts
> +export { mountWebComponent };
because in a storybook, you will see the empty page when you switch from one tab to another.
if you call `mountWebComponent` only ones at the end of the file.

watch this code below
```
import React from 'react';
import { storiesOf } from '@storybook/react';
import { mountWebComponent } from './src/example';

class Example extends React.Component {
  async componentDidMount() {
    await mountWebComponent();
  }

  render() {
    return <div id="web-modal" />;
  }
}

storiesOf('Modal', module).add('default', () => <Example />);
```

2019-06-20 12:37 UTC, 95kach commented on packages/modal/cypress/integration/modal.test.js
> +describe('Modal TCs', () => {
Where? I don't see any package where I can find ts inside cypress folder.

In case when in each package we use this approach I will follow the same in mine.
But till now it's not a common approach.

@dmitriyslaym

2019-06-20 12:43 UTC, 95kach commented
prettify ignore in fixtures BECAUSE OF THIS 
`Error: 'modal.js' is not a valid JavaScript object.SyntaxError: Unexpected token ;`

Cypress can correctly use fixtures after prettifier `;` I don't know.

2019-06-20 13:54 UTC, dmitriyslaym commented on packages/modal/cypress/integration/modal.test.js
> +describe('Modal TCs', () => {
@95kach 
https://github.com/jivygroup/exchange-sandbox/tree/develop/packages/layout-component/cypress

But as I told you - this is a remark for future

2019-06-20 13:56 UTC, dmitriyslaym commented on packages/modal/src/index.ts
> +export default Modal;
You call PR "Modal extension".
Are you going to include this component in Wokspace configuration?

2019-06-20 15:52 UTC, 95kach commented on packages/modal/cypress/integration/modal.test.js
> +describe('Modal TCs', () => {
I got you, thanks!

2019-06-21 06:30 UTC, 95kach commented on packages/modal/src/index.ts
> +export default Modal;
no

2019-06-21 07:00 UTC, dmitriyslaym approved these changes

2019-06-21 07:00 UTC, merged